export const fileConstants = {
  GET_FILES_SUCCESS: "GET_FILES_SUCCESS",
  GET_FILES_FAILURE: "GET_FILES_FAILURE",

  MOVE_FILE_SUCCESS: "MOVE_FILE_SUCCESS",
  MOVE_FILE_FAILURE: "MOVE_FILE_FAILURE",

  MOVE_FOLDER_SUCCESS: "MOVE_FOLDER_SUCCESS",
  MOVE_FOLDER_FAILURE: "MOVE_FOLDER_FAILURE",

  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",

  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",
};
